Corona App/Pages/Kunder/Adgangskoder/GlemtAdgangskodeTLF.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Corona_App.Pages.Kunder.Adgangskoder
{
    public class GlemtAdgangskodeTLFModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Corona App/Pages/Kunder/Bruger/Betaling.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Corona_App.Pages.Kunder.Bruger
{
    public class BetalingModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Corona App/Pages/Kunder/Bruger/BlivBud.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Corona_App.Pages.Kunder.Bruger
{
    public class BlivBudModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Corona App/Pages/Kunder/Bruger/NuværendeOpgave.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Corona_App.Pages.Varer;

namespace Corona_App.Pages.Kunder.Bruger //Lavet Af Marcus & Jonathan
{
    public class NuværendeOpgaveModel : PageModel
    {
        public IVare _katelog;

        public List<Bestilling> KundensVare { get; set; }
        [BindProperty]
        public List<Bestilling> b { get; set; }

        [BindProperty]
        public string SearchText { get; set; }

        public NuværendeOpgaveModel(IVare katelog)
        {
            _katelog = katelog;
        }

        public void OnGet()
        {
            b = _katelog.KundensVare.FindAll(k => k.Id == 7);
            KundensVare = _katelog.KundensVare;
        }

        public IActionResult OnGetSlet()
        {
            KundensVare = _katelog.KundensVare;
            return RedirectToPage("kurv");
        }
        public void OnPost()
        {
            b = _katelog.KundensVare.FindAll(k => k.Id == 7);
        }

    }
}

Corona App/Pages/Kunder/Bruger/OpgaverINærhedenAfDig.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Corona_App.Pages.Varer;

namespace Corona_App.Pages.Kunder.Bruger //Lavet Af Marcus & Jonathan
{
    public class OpgaverINærhedenAfDigModel : PageModel
    {
        private IVare _katelog;
        private IKunde _kunde;

        public int AntalVare { get; set; }
        public IVare SamletPris { get; set; }
        public List<Bestilling> KundensVare { get; set; }
        [BindProperty]
        public BrugerInfo b { get; set; }
        [BindProperty]
        public List<BrugerInfo> bList { get; set; }

        public OpgaverINærhedenAfDigModel(IVare katelog, IKunde kunde)
        {
            _katelog = katelog;
            _kunde = kunde;
        }
        public void OnGet()
        {
            bList = _kunde.Bruger;


            KundensVare = _katelog.KundensVare;
            SamletPris = _katelog;
            b = _kunde.GetSingle(3);
        }

        public void OnPost()
        {
            KundensVare = _katelog.KundensVare;
            bList = _katelog.SearchBestilling(b);
            SamletPris = _katelog;
        }
    }
}

Corona App/Pages/Kunder/Bruger/Velkommen.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Corona_App.Pages.Kunder.Bruger
{
    public class VelkommenModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Corona App/Pages/Kunder/Indkøbsliste.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Corona_App.Pages.Varer //Lavet Af Marcus
{
    public class IndkøbslisteModel : PageModel
    {
        private IVare _katelog;
        public List<Bestilling> b { get; set; }
        public string ErrorMsg { get; set; }

        public IndkøbslisteModel(IVare katelog)
        {
            _katelog = katelog;
        }

        public void OnGet()
        {
            b = _katelog.KundensVare.FindAll(k => k.Id == 7);
        }
        public IActionResult OnGetSlet(int vareNr)
        {
            try
            {
                _katelog.SletVareFraBestilling(vareNr);
                b = _katelog.KundensVare.FindAll(k => k.Id == 7);
            }
            catch (ArgumentNullException n)
            {
                ErrorMsg = n.ParamName;
            }
            return Page();
        }

        public void OnPost()
        {
            b = _katelog.KundensVare.FindAll(k => k.Id == 7);
        }
    }
}

Corona App/Pages/Kunder/Kurv.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Corona_App.Pages.Varer;

namespace Corona_App.Pages.Kunder //Lavet Af Marcus & Jonathan
{
    public class KurvModel : PageModel
    {
        public IVare _katelog;

        public string ErrorMsg { get; set; }

        public List<Bestilling> KundensVare { get; set; }
        [BindProperty]
        public List<Bestilling> b { get; set; }

        [BindProperty]
        public string SearchText { get; set; }

        public KurvModel(IVare katelog)
        {
            _katelog = katelog;
        }

        public void OnGet(int id)
        {
            b = _katelog.KundensVare.FindAll(k => k.Id == id);
            KundensVare = _katelog.KundensVare;
        }

        public void OnPost()
        {
            b = _katelog.KundensVare.FindAll(k => k.Id == 7);
            KundensVare = _katelog.KundensVare;
        }

        public IActionResult OnGetSlet(int vareNr) // sletter varen fra kundens bestilling
        {
            try
            {
                _katelog.SletVareFraBestilling(vareNr);
                KundensVare = _katelog.KundensVare;
            }
            catch (ArgumentNullException n)
            {
                ErrorMsg = n.ParamName;
            }

            return RedirectToPage("kurv");
        }

    }
}

Corona App/Pages/Kunder/inkøbsk.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Corona_App.Pages.Kunder
{
    public class inkøbskModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Corona App/Pages/Kunder/Bruger.cshtml
@page "{id}"
@model Corona_App.Pages.Shared.Kunder.BrugerModel
@{
    ViewData["Title"] = "Profil";
}
<div class="container">
    <h1>Profil</h1>
    <div class="row">
        <div class="col-md-4">
            <form method="post">
                <input type="hidden" asp-for="b.Id" />

                @* felt til navn, viser den pågældendes brugers information *@
                <div class="form-group">
                    <label> Navn: </label>
                    <input type="text" asp-for="b.Navn" class="form-control" />
                    <span asp-validation-for="b.Navn" class="alert-danger"></span>
                </div>
                  

                <div class="form-group">
                    <label>Adresse:</label>
                    <input type="text" asp-for="b.Adresse" class="form-control" />
                    <span asp-validation-for="b.Adresse" class="alert-danger"></span>
                </div>

                <div class="form-group">
                    <label>Tlf nummer</label>
                    <input type="text" asp-for="b.Mobilnummer" class="form-control" />
                    <span asp-validation-for="b.Mobilnummer" class="alert-danger"></span>
                </div>

                <div class="form-group">
                    <label>Email</label>
                    <input type="text" asp-for="b.Email" class="form-control" />
                    <span asp-validation-for="b.Email" class="alert-danger"></span>
                </div>

                <div class="form-group">
                    <label>Adgangskode</label>
                    <input type="text" asp-for="b.Adgangskode" class="form-control" />
                    <span asp-validation-for="b.Adgangskode" class="alert-danger"></span>
                </div>

                <div class="form-group knap">
                    <input type="submit" value="Gem ændringer" class="btn btn-primary knap" />
                </div>

                <div class="form-group knap2">
                    <input type="submit" value="Slet bruger" class="btn btn-danger knap2" />
                </div>
                
            </form>
        </div>
    </div>
</div>

Corona App/Pages/Kunder/Indkøbsliste.cshtml
@page
@model Corona_App.Pages.Varer.IndkøbslisteModel
@*Lavet Af Cecilie*@
@{
    ViewData["Title"] = "Indkøbsliste";
}

<header>
    <form method="post">
        <div>
            <input type="submit" value="Tilbage" class="btn rema_farve" formaction="/Varer/KatalogVarer/Katalog" />
        </div>
    </form>
</header>
<div class="container, text-center">
    <div class="image">
        <h1>Indkøbsliste</h1>
        <img src="~/Billeder/images.jfif" alt="i" />
    </div>


    @foreach (var item in Model.b)
    {
        <div class="opgave_border Bredde100 little_margin_top">
            <div class="dropdown-item container_dropdown_item">

                <img src="https://www.dummyimage.com/40px40px" alt="Alternate Text" />
                <div>
                    <p class="display_inline">@item.Navn </p>
                    <p class="display_inline float-right">@item.Pris kr.</p>
                    <a type="submit" asp-page-handler="slet" class="btn rema_farve" asp-route-vareNr="@item.VareNr"> slet </a>
                </div>
            </div>
        </div>
    }




    <form action="/action_page.php" class="text-center">
        Kommentar til ordre:<br>
        <textarea name="explanation" dirname="explanation.dir"></textarea>
        <div class="form-group betal">
            <input type="submit" value="Betal" formaction="/Kunder/Bruger/Betaling" class="btn btn-primary betal" />
        </div>
    </form>

</div>

<nav class="menuknapper">
    <div class="rowtest">
        <form method="get">
            <div class="columntest"><input type="submit" formaction="/Varer/KatalogVarer/Katalog" value="Varer" class="skaler btn btn-primary"></div>
        </form>
        <form method="get">
            <div class="columntest"><input type="submit" formaction="/Kunder/Indkøbsliste" value="Indkøbsliste" class="skaler btn btn-primary"></div>
        </form>
        <form method="get">
            <div class="columntest"><input type="submit" formaction="/Kunder/Bruger/BlivBud" value="Bliv Bud" class="skaler btn btn-primary"></div>
        </form>
        <form method="get">
            <div class="columntest"><input type="submit" formaction="/Kunder/Bruger/Bruger/3" value="Profil" class="skaler btn btn-primary"></div>
        </form>
    </div>
</nav>

Corona App/Pages/Kunder/Kurv.cshtml
@page "{id}"
@model Corona_App.Pages.Kunder.KurvModel
@{
}

<body>
    <header>
        <form method="post">
            <div>
                <input type="submit" value="Tilbage" class="btn rema_farve" formaction="/Kunder/Bruger/OpgaverINærhedenAfDig" />
            </div>
        </form>
    </header>
    <div class="container text-center">
        <div class="image text-center">
            <h1 class="text-center">Indkøbsliste</h1>
            <img src="~/Billeder/images.jfif" alt="i" />
        </div>

        @foreach (var item in Model.b)
        {
            <div class="opgave_border Bredde100 little_margin_top ">
                <div class="dropdown-item container_dropdown_item">

                    <img src="https://www.dummyimage.com/40px40px" alt="Alternate Text" />
                    <div>
                        <p class="display_inline">@item.Navn </p>
                        <p class="display_inline float-right">@item.Pris kr.</p>
                    </div>
                </div>
            </div>
        }

        <form class="text-center">
            Kommentar til ordre:<br>
            <textarea name="explanation" dirname="explanation.dir"></textarea>
        </form>
        <form class="text-center" method="post">
            <input type="submit" class="btn rema_farve btn-primary" value="Kvittering" formaction="/Kunder/Bruger/Velkommen" />
        </form>
    </div>
</body>

Corona App/Pages/Kunder/OpretKunde.cshtml
@page
@model Corona_App.Pages.Kunder.OpretKundeModel
@{
    ViewData["Title"] = "Opret bruger";
}
<div class="container">
    <div class="text-center">
        <h1>Opret Bruger</h1>
    </div>
    <div class="row">
        <div class="col-md-4">
            <form method="post">

                @* Felt til at skrive ens navn, og kommer med en validation alert hvis man skriver noget forkert *@
                <div class="form-group">
                    <label>Fulde navn</label>
                    <input type="text" asp-for="b.Navn" class="form-control" />
                    <span asp-validation-for="b.Navn" class="alert-danger"></span>
                </div>

                <div class="form-group">
                    <label>Mobil nummer</label>
                    <input type="text" asp-for="b.Mobilnummer" class="form-control" />
                    <span asp-validation-for="b.Mobilnummer" class="alert-danger"></span>
                </div>

                <div class="form-group">
                    <label>Adresse</label>
                    <input type="text" asp-for="b.Adresse" class="form-control" />
                    <span asp-validation-for="b.Adresse" class="alert-danger"></span>
                </div>

                <div class="form-group">
                    <label>Email</label>
                    <input type="text" asp-for="b.Email" class="form-control" />
                    <span asp-validation-for="b.Email" class="alert-danger"></span>
                </div>

                <div class="form-group">
                    <label>Adgangskode</label>
                    <input type="text" asp-for="b.Adgangskode" class="form-control" />
                    <span asp-validation-for="b.Adgangskode" class="alert-danger"></span>
                </div>

                <p>Dit Tlf nummer skal være forbundet til en mobilepay konto, for at du kan modtage penge til at købe ind for andre</p>

                @* Checkbox til ´accept af handelsbetingelser *@
                <div class="text-center">
                    <label>
                        <input type="checkbox" />
                        Acepter vores handelsbetingelser
                    </label>
                </div>


                <p><a href="https://shop.rema1000.dk/handelsbetingelser">Læs vores handelsbetingelser her</a></p>

                 <div class="form-group">
                      <input type="submit" value="Opret bruger" class="btn btn-primary opret" />
                 </div>
            </form>
        </div>
    </div>
</div>
    
 

Corona App/Pages/Kunder/inkøbsk.cshtml
@page
@model Corona_App.Pages.Kunder.inkøbskModel
@{
}